### ISSUE TITLE
Installation on Win7 x64 fails with "The server is not operational"

### ISSUE THREAD

**Issue by gavanderhoorn** [codenotes/ros_cygwin#3]
Trying to install [ros-indigo.exe](https://github.com/codenotes/ros_cygwin/releases/download/1.0/ros-indigo.exe) v1.0 on a Windows 7 x64 machine. Clicking on the *Install* button does not seem to result in any activity, and after a short time a dialogue pops up telling me that "The server is not operational":

![setup1](https://cloud.githubusercontent.com/assets/4550046/15314216/c776d23a-1c10-11e6-80f8-96d0429c944a.png)

I realise "win7 x64" is rather vague. Anything I can do to debug?

**Comment by codenotes** [comment]
Can you try the jade install and see if that works?

We used to have an issue with the installer on windows 7 where if the domain name and/or machine name had certain characters, it would fail.  The installer adjusts file permissions on the cygwin install and uses the doman/machine name to do that...cygwin had issue with certain syntax that windows was ok with.

I believe this is fixed in the jade installer but not in the indigo one.   The indigo distro hasn't been updated in awhile.  Can you try jade and let us know?

**Comment by gavanderhoorn** [comment]
Just tested the Jade installer: same problem.

**Comment by gavanderhoorn** [comment]
This is a non domain-joined machine, if that makes a difference.

**Comment by codenotes** [comment]
Yes, could be that.  Are you joined to some kind of "workgroup"?   There is some sophisticated permission setting required that involves domain credentials and the installer can choke there.  Let me look into that, I had believed we fixed that for Jade, but apparently not well enough.  Also, can you tell me your machine name and whatever domain/workgroup it sees itself as connected to?

**Comment by codenotes** [comment]
Also, hate to ask you this...but do you have a windows 8 or greater machine anywhere you could try this out on?  Maybe a VM?  Would help me be sure...we have had W7 issues in the past and we haven't used W7 for awhile.

**Comment by codenotes** [comment]
I am uploading a different rev of the installer, stand by.

**Comment by gavanderhoorn** [comment]
> Yes, could be that. Are you joined to some kind of "workgroup"?

No, this is a completely stand-alone machine, has never been joined to any domain. No 'homegroup' stuff going on either.

> Also, can you tell me your machine name and whatever domain/workgroup it sees itself as connected to?

According to `systeminfo`:
```
Domain:                    WORKGROUP
Logon Server:              \\PIET
```

**Comment by gavanderhoorn** [comment]
> Also, hate to ask you this...but do you have a windows 8 or greater machine anywhere you could try this out on? Maybe a VM? Would help me be sure...we have had W7 issues in the past and we haven't used W7 for awhile. 

I can test this, but not today.

**Comment by codenotes** [comment]
Actually, don't test...I am uploading a patched version of the installer right now.  It is large, so will take a bit, but I will have it up and that SHOULD work for W7.

**Comment by sysprogs** [comment]
OK, the latest one for Jade should be called Cygwin-jade6.exe (md5 814612b7b71a1b2160078f0c22368912). Is that the one you are uploading?

With Indigo, there’s an archive from 12th Nov 2015 that can be combined with the new installer. I can send you the necessary parts and a brief instruction, or can build, verify installation and upload it to the releases section for $300. It should have rviz, but probably not OMPL and related packages as they were built late December. I can just send you the archive so you can test it out yourself before deciding whether you want it publicly released. 

You can also try searching for cygwin-indigo.tar.xz (md5 09888dc95c1284d7e12cc334d40d6bbe) on your machines, as you probably already have it.

 

Can also schedule a rebuild of Indigo with the latest patches (but IIRC, we decided to drop support for it, so the patches may need adjustment). My brief estimate is ½-2 days depending on how many things are broken.

 

----

Best regards,

Ivan Shcherbakov

**Comment by codenotes** [comment]
OK, a much newer installer is up there, release 1.1.  Give that a try.

**Comment by gavanderhoorn** [comment]
Just tested `cygwin-jade6.exe`: installs successfully now.

**Comment by codenotes** [comment]
Great...you should be able to install indigo also side by side if you like.  The two should not interfere.

As far as size, yes...they are huge.  We've had to include binaries and libraries for many components in ROS (since there is no apt-get or incremental way of getting them) and that has made the installation very large.   We can put an install size indication in the next rev of installs and I will note the sizes in the readme.

**Comment by gavanderhoorn** [comment]
> As far as size, yes...they are huge

Just noticed that the `/opt` folder contains all three of `build_isolated`, `devel_isolated` and `install_isolated`. I'm not sure how much you've modified the setup and installation scripts, but typically only either `build_isolated` or `install_isolated` should be needed for normal usage.

Do you have any specific reason for including the build and devel folders as well?

Omitting them from the installation would reduce the installed footprint by about 2.5GB.

**Comment by gavanderhoorn** [comment]
Moved to my last comment to #5.

**Comment by gavanderhoorn** [comment]
Not sure about the newest installer(s), but at least the version tested (1.1) worked on Win7x64, so closing.

Thanks for the support :100:
