### ISSUE TITLE
ROS install fails with "Decompressing failed:Pipe is broken" and "TAR Unpacking failed: Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by jfstepha** [codenotes/ros_cygwin#4]
My issue appears to be similar to one of the previous issues, but I'm using the new (1.1) installer:

![image](https://cloud.githubusercontent.com/assets/2347223/15622933/32fde0c4-243c-11e6-958d-ee7c7533a5df.png)

I tried both the jade and the indigo, both failed.  
I tried running as administrator, no luck.
I tried connecting to the domain, no luck.

My computer name is "jfstepha-MOBL5", and the domain is "amr.corp.intel.com".  I cannot change it.
I'm running Windows 8.1, 64 bit.

Thanks.

**Comment by sysprogs** [comment]
OK, we have added verbose logging support to the installer. Please re-download the v1.1 (Indigo) installer, run it again and select "Write Installation log". Then please look at the end of the <Install directory>\rosinstall.log file for relevant error messages. Feel free to post them here for further troubleshooting advice.

**Comment by jfstepha** [comment]
I re-downloaded cygwin-indigo from https://github.com/codenotes/ros_cygwin/releases, but it is binary-identical to the version I downloaded before.  Was I supposed to get it from somewhere else?

**Comment by codenotes** [comment]
Try the v1.21 release of the indigo installer.   I am sorry you are having difficulties; we'll get to the bottom of the issue.

**Comment by jfstepha** [comment]
Ok, here you go:
```
Initializing unpacker...
Obtaining SIDs for user and group...
Current user: AMR\jfstepha, SID = S-1-5-21-725345543-602162358-527237240-12938
Machine name: JFSTEPHA-MOBL5, domain name: AMR
Domain-joined machine: obtaining group SID from LDAP://AMR...
Searching for (&(objectClass=user) (cn= jfstepha))...
Exception during unpacking: System.Runtime.InteropServices.COMException (0x8007203A): The server is not operational.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   at System.DirectoryServices.DirectorySearcher.FindOne()
   at ROSInstaller.CygwinACLMapper..ctor(StreamWriter logStream)
   at ROSInstaller.CygwinTarUnpacker..ctor(Stream stream, String targetDir, StreamWriter logStream)
   at ROSInstaller.ROSInstallTask.TarExtractThreadBody()
```

**Comment by sysprogs** [comment]
OK, it looks like your computer cannot reach the domain controller and the installer cannot figure out the primary group ID to set proper file permissions for Cygwin. Please double-check your connectivity to the domain controller.

**Comment by codenotes** [comment]
If you are wondering why access to the domain controller matters, it is because packaging an installed cygwin environment and deploying it on a new machine involves a great deal of file re-permissioning to the installing user.  Towards that end, if the installer can't establish your credentials it is unable to modify the permissions.

**Comment by jfstepha** [comment]
Yes, I was wondering.  That seems a bit unusual.  

I tried it both at home with VPN and now in the office, it fails with:
![image](https://cloud.githubusercontent.com/assets/2347223/15673926/ec11751c-2707-11e6-8b92-ad7829481495.png)

And the log looks like this:
`Initializing unpacker...
Obtaining SIDs for user and group...
Current user: AMR\jfstepha, SID = S-1-5-21-725345543-602162358-527237240-12938
Machine name: JFSTEPHA-MOBL5, domain name: AMR
Domain-joined machine: obtaining group SID from LDAP://AMR...
Searching for (&(objectClass=user) (cn= jfstepha))...
Exception during unpacking: System.Exception: Failed to identify the primary group for the current user
   at ROSInstaller.CygwinACLMapper..ctor(StreamWriter logStream)
   at ROSInstaller.CygwinTarUnpacker..ctor(Stream stream, String targetDir, StreamWriter logStream)
   at ROSInstaller.ROSInstallTask.TarExtractThreadBody()`

**Comment by sysprogs** [comment]
This generally means that some configuration error is preventing your computer from accessing the domain controller. The Windows error logs may contain more details. What happens when you try to share a folder and explicitly grant access to some domain users? Does Windows Explorer show the user list or do you get an error?

**Comment by jfstepha** [comment]
Yep, I'm on the domain.  Yes, I successfully shared a folder, and checked the user list to make sure.

**Comment by codenotes** [comment]
J,

Firstly, I am sorry you are having this trouble.  Will work with you until we get to the bottom of it...what we are needing to do with cygwin is a bit nouveau edge.

This is a lot to ask, but I'd really love to know if this domain specifically is related or not; would it be a lot of trouble to take your home computer off the domain and just put it on a local workgroup temporarily and then try the install?   I don't know to what degree your central administrator controls your home machine, so this may not be possible. But if it is, maybe create a new account with local admin rights who is not affiliated with any external domain to see how the installer responds. 

Ivan: Is it feasible for him to try the manual untaring from a new cygwin install?  

Best,
Gregory

**Comment by codenotes** [comment]
J,

Also, probably you are but, are you using the latest binary installler, 1.21?

**Comment by VictorLamoine** [comment]
I'm trying to install this on my personal computer, Windows 10:

![config_w10](https://cloud.githubusercontent.com/assets/5566160/15806339/8523bc64-2b41-11e6-8b3a-c4566038ca4c.png)


- I tried both Indigo and Jade latest binaries.
- I tried executing as administrator.
- I don't understand what I should do with the domain name

Indigo installer log: (Is there a way to log in English?)
```
Initializing unpacker...
Obtaining SIDs for user and group...
Current user: DESKTOP-VICTOR\Victor, SID = S-1-5-21-3957116300-3393805498-1814692729-1001
Machine name: DESKTOP-VICTOR, domain name: DESKTOP-VICTOR
Non-domain machine: obtaining group SID from local directory...
Exception during unpacking: System.Runtime.InteropServices.COMException (0x80005004): Un objet répertoire inconnu a été demandé

   à System.DirectoryServices.DirectoryEntries.Find(String name, String schemaClassName)
   à ROSInstaller.CygwinACLMapper..ctor(StreamWriter logStream)
   à ROSInstaller.CygwinTarUnpacker..ctor(Stream stream, String targetDir, StreamWriter logStream)
   à ROSInstaller.ROSInstallTask.TarExtractThreadBody()

```

I can try anything you ask as this is my personal machine, but please give directions as I'm pretty newbie on Windows.

**Comment by gavanderhoorn** [comment]
Could this be a locale issue?

**Comment by VictorLamoine** [comment]
Oh right, I forgot to mention that my machine is in French.

**Comment by codenotes** [comment]
apologies on late reply. We just completed a new installer, lets try that...github is having some issues taking our release, but here it is:

https://s3.amazonaws.com/sysprogs2infusion/cygwin-indigo7.exe

**Comment by codenotes** [comment]
actually, release updated, give v1.23 a try.  These are new installers written in C (as opposed to .NET) which we hope will do a better job with permissioning.

**Comment by jfstepha** [comment]
cygin-indigo7 works!

I couldn't get v1.23 to work, I'm not sure why.

**Comment by VictorLamoine** [comment]
It works for me too, I didn't test a lot but I can `catkin_make` etc.
Thanks!

**Comment by codenotes** [comment]
All right!  So glad it worked...and BTW, if you are doing C++ ROS stuff in cygwin (or android), check out this tool (http://visualgdb.com/) ...I could not live or develop meaningfully without it. Let's me work in Visual Studio which, for Windows dev, is a necessity for me.
